[package]
name = "parquet00"
version = "0.1.0"
authors = ["Gustavo De la Cruz <gusdelact@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parquet = "0.14.0"
