[package]
name = "arrow01"
version = "0.1.0"
authors = ["hadoop"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = "0.14.0"
datafusion = "0.14.0"
